sudo: false
language: php

services:
  - mysql

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install --dev --no-interaction
  - composer require satooshi/php-coveralls
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:create
  - php app/console doctrine:fixtures:load -n

script:
  #- phpunit -c app --coverage-text
  - mkdir -p build/coverage
  - phpunit -c app --coverage-text --coverage-clover build/coverage/clover.xml
  - bin/coveralls -v

#after_success:
#  - bin/coveralls -v
