sudo: false
language: php

services:
  - mysql

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:create
  - php app/console doctrine:fixtures:load -n

script: phpunit -c app --coverage-text

notifications:
  email:
    - maxence.poutord@gmail.com
