sudo: false
language: php

services:
  - mysql

php:
  - 5.6
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer self-update
  - composer install --dev --no-interaction
  - composer require satooshi/php-coveralls
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:create
  - php app/console doctrine:fixtures:load -n

script:
  - mkdir -p build/logs
  - phpunit -c app --coverage-text --coverage-clover build/logs/clover.xml
  - bin/coveralls -v
